# Generated by Django 3.1.6 on 2021-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('starting_bid', models.FloatField()),
                ('category', models.CharField(max_length=64)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
