# Generated by Django 3.1.6 on 2021-02-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='WatchList',
        ),
    ]
